// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1vuSn7IKEgpYho_4WnxNrmS61jHm1OQ',
    appId: '1:1052487046397:web:178b624042ce2a92a5da94',
    messagingSenderId: '1052487046397',
    projectId: 'bookreco-b8534',
    authDomain: 'bookreco-b8534.firebaseapp.com',
    storageBucket: 'bookreco-b8534.appspot.com',
    measurementId: 'G-SKGXF88R9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoulDwFZ3LGyx-VNSBpk3wa3oF-loX-CM',
    appId: '1:1052487046397:android:fc91e1038b1b8eb2a5da94',
    messagingSenderId: '1052487046397',
    projectId: 'bookreco-b8534',
    storageBucket: 'bookreco-b8534.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-qu6fvS1kZlaCSHHJHPFxy2Lg_xDMkQ',
    appId: '1:1052487046397:ios:779935a49843e9bca5da94',
    messagingSenderId: '1052487046397',
    projectId: 'bookreco-b8534',
    storageBucket: 'bookreco-b8534.appspot.com',
    iosClientId: '1052487046397-fek7f54j0lgjfnhdccp2op843ecrtdub.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookreco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-qu6fvS1kZlaCSHHJHPFxy2Lg_xDMkQ',
    appId: '1:1052487046397:ios:c30c1d2b1d2a8ffca5da94',
    messagingSenderId: '1052487046397',
    projectId: 'bookreco-b8534',
    storageBucket: 'bookreco-b8534.appspot.com',
    iosClientId: '1052487046397-bgh28a15rlkuujikeeu8ht780fbfclui.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookreco.RunnerTests',
  );
}
